
homeassistant: !include home_assistant.yaml

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts: !include tts.yaml

automation: !include automations.yaml
automation mine: !include_dir_named automations/

script: !include_dir_named scripts/

scene: !include scenes.yaml
scene mine: !include_dir_named scenes/
