
# Loads default set of integrations. Do not remove.
default_config:

homeassistant: !include home_assistant.yaml

# Text to speech
tts: !include tts.yaml

automation: !include automations.yaml
automation mine: !include_dir_list automations/

script: !include scripts.yaml
script mine: !include_dir_list scripts/

scene: !include scenes.yaml
scene mine: !include_dir_list scenes/