id: 'kids_bathroom_fan_on_humiditity'
alias: 'Kids Batroom Fan On Humidity'
mode: single
trigger:
  platform: numeric_state
  entity_id: sensor.kids_bathroom_humidity
  above: 90.0
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.kids_shower_fan
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.kids_shower_fan