id: 'pantry_light_on_motion'
alias: 'Pantry light on Motion'
mode: restart
trigger:
  platform: state
  entity_id: binary_sensor.pantry_motion_sensor_motion
  from: 'off'
  to: 'on'
condition: []
action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.pantry_light
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.pantry_light